feat: add pre commit and docker compose

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -19,13 +19,25 @@ if [[ ! $branch_name =~ $valid_pattern ]]; then
   exit 1
 fi
 
-# # Run linting
-# echo "🧹 Running ESLint..."
-# bun run lint
+# Run Frontend precommit check
+# echo "🧹 Running Frontend Precommit check..."
+# . "frontend/.husky/pre-commit"
 # if [ $? -ne 0 ]; then
-#   echo "❌ Linting failed. Please fix the issues before committing."
+#   echo "❌ Frontend precommit check failed. Please fix the issues before committing."
 #   exit 1
 # fi
+
+echo "🧹 Running Prettier on staged files..."
+prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
+
+# Run Backend precommit check
+echo "🧹 Running Backend Precommit check..."
+cd backend
+npm run lint:check && npm run type-check
+if [ $? -ne 0 ]; then
+  echo "❌ Backend precommit check failed. Please fix the issues before committing."
+  exit 1
+fi
 
 # # Run type checking
 # echo "🔍 Running TypeScript type checking..."
